# Generated by Django 5.2.3 on 2025-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('it_support', 'IT Support')], default='student', max_length=20),
        ),
    ]
