# Generated by Django 5.2.5 on 2025-08-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0001_initial'),
        ('students', '0004_link_students_to_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_class',
            field=models.ForeignKey(blank=True, help_text='Current class/grade of the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='results.studentclass'),
        ),
    ]
