# Generated by Django 5.2.5 on 2025-08-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0001_initial'),
        ('students', '0005_studentprofile_current_class'),
    ]

    operations = [
        # Preserve the existing string data by renaming the current CharField
        migrations.RenameField(
            model_name='academicstatus',
            old_name='current_class',
            new_name='old_current_class',
        ),
        # Add a new nullable FK field that will be populated in a later data migration
        migrations.AddField(
            model_name='academicstatus',
            name='current_class_fk',
            field=models.ForeignKey(blank=True, help_text='Temporary FK to StudentClass while migrating data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_statuses_tmp', to='results.studentclass'),
        ),
    ]
