# Generated by Django 5.2.5 on 2025-08-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0001_initial'),
        ('students', '0008_link_academicstatus_to_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstatus',
            name='current_class',
            field=models.ForeignKey(blank=True, help_text='Class/grade for this academic status record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_statuses', to='results.studentclass'),
        ),
    ]
