# Generated by Django 5.2.3 on 2025-06-24 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffprofile_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffprofile_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teachertimetable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('admin', 'Administration'), ('accounts', 'Accounts'), ('it', 'IT'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('it_support', 'IT Support'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='teachertimetable',
            unique_together={('staff', 'day_of_week', 'period')},
        ),
        migrations.CreateModel(
            name='StaffNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_created', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='notices', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staffprofile')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
