# Generated by Django 5.2.3 on 2025-06-25 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='elibraryresource',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('students', 'Students Only'), ('staff', 'Staff Only'), ('admin', 'Administrators Only'), ('parents', 'Parents Only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='When this announcement should no longer be visible', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='When this announcement should become visible', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='download_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='file_size',
            field=models.PositiveIntegerField(editable=False, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Grade/Class level this resource is intended for', max_length=50),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='resource_type',
            field=models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('worksheet', 'Worksheet'), ('video', 'Video'), ('audio', 'Audio'), ('presentation', 'Presentation'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='elibraryresource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='elibrary/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-priority', '-created_at'], name='academics_a_is_acti_18c429_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['audience', 'is_active'], name='academics_a_audienc_af6dad_idx'),
        ),
        migrations.AddIndex(
            model_name='classtimetable',
            index=models.Index(fields=['class_name', 'day_of_week'], name='academics_c_class_n_85b958_idx'),
        ),
        migrations.AddIndex(
            model_name='elibraryresource',
            index=models.Index(fields=['resource_type', '-uploaded_at'], name='academics_e_resourc_f4c2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='elibraryresource',
            index=models.Index(fields=['subject', 'grade_level'], name='academics_e_subject_00f987_idx'),
        ),
    ]
