# Generated by Django 5.2.4 on 2025-07-03 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_announcement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='academics_a_is_acti_18c429_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='academics_a_audienc_af6dad_idx',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='attachment',
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['audience', 'is_active', '-created_at'], name='academics_a_audienc_db7063_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['priority', '-created_at'], name='academics_a_priorit_0c4f03_idx'),
        ),
    ]
