# Generated by Django 5.2.3 on 2025-06-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_payment_notes_payment_receipt_number'),
    ]

    operations = [
    ]
