# Generated by Django 5.2.3 on 2025-06-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_add_performance_indices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='accounting__date_2c9cc2_idx',
            old_name='accounting__date_9c7d8c_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='accounting__created_b3703d_idx',
            old_name='accounting__created_910db7_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='accounting__payment_a45b9d_idx',
            old_name='accounting__payment_2a9141_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='accounting__created_97c0b2_idx',
            old_name='accounting__created_fd4132_idx',
        ),
        migrations.RenameIndex(
            model_name='tuitionfee',
            new_name='accounting__student_4329bb_idx',
            old_name='accounting__student_b2ad3d_idx',
        ),
        migrations.RenameIndex(
            model_name='tuitionfee',
            new_name='accounting__status_3bd624_idx',
            old_name='accounting__status_9e4141_idx',
        ),
    ]
