# Generated by Django 5.2.4 on 2025-07-06 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow Statement'), ('fee_collection', 'Fee Collection Report'), ('expense_report', 'Expense Report')], max_length=20)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='financial_reports/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('report_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', '-generated_at'], name='accounting__report__f07522_idx'), models.Index(fields=['generated_by', '-generated_at'], name='accounting__generat_90cf0f_idx')],
            },
        ),
    ]
